[dunecontrol] check for left over la files
if the user has for some reason old la files from the autotools era,
these can lead to very subtle and hard to understand errors. We now
check for old la files and bail out in case some are found.

diff --git a/bin/dunecontrol b/bin/dunecontrol
--- a/bin/dunecontrol
+++ b/bin/dunecontrol
@@ -715,6 +715,10 @@ run_default_configure () {
       test -d "$ABS_BUILDDIR" || mkdir -p "$ABS_BUILDDIR"
       SRCDIR="$PWD"
       cd "$ABS_BUILDDIR"
+      # check for libtool libs, which might break modules depending on this module
+      test -n "`find -name \*.la`" && \
+          echo "Error: your build directory $ABS_BUILDDIR contains libtool built libraries, please cleanup" && \
+          exit 1
       echo "$PREPARAMS $CMAKE -DCMAKE_MODULE_PATH=\"$CMAKE_MODULE_PATH\" $CMAKE_PARAMS $CMAKE_FLAGS \"$SRCDIR\""
       eval $PREPARAMS $CMAKE "-DCMAKE_MODULE_PATH=\"$CMAKE_MODULE_PATH\" $CMAKE_PARAMS $CMAKE_FLAGS \"$SRCDIR\"" || exit 1
     else
