Try to make it work on opensolaris: * SunOS basic regexps are very /basic/: no support for character classes like   [:alnum:], no '+' (not even '\+') and the greediness of stuff like '\{m,n\}'   is not well defined, which is a problem in sed 's/.../.../' (according to   the man page, it should work only with regular expressions matching a single   character, i.e. not with '\(...\)').  Therefore, a lot of parsers had to be   rewritten, especially the one for (versioned) dependencies. * Don't use grep's -q option, it's not portable.  Use >/dev/null instead. * Awk on SunOS is very basic as well.
Currently it still fails in configure, but at least it gets there...


[[Imported from SVN: r5400]]

diff --git a/bin/dune-autogen b/bin/dune-autogen
--- a/bin/dune-autogen
+++ b/bin/dune-autogen
@@ -12,8 +12,15 @@ usage () {
 }
 
 ## get my name...
-grep -q '^Module:' dune.module || echo "Parser Error: Module entry missing in dune.module"
-name=`awk '{ sub(/:/,": ") }; /^Module:/ { print $2 }' dune.module`
+grep '^Module:' dune.module >/dev/null || echo "Parser Error: Module entry missing in dune.module"
+name=
+while read head name rest
+do case "$head" in
+   Module:) break;;
+   Module:*) name="${head#Module:}"; break;;
+   esac
+   name=
+done <dune.module
 
 ## dune-all.m4
 rm -f dune-all.m4
