[Buildsystem] Fixes quoting with spaces inside dune-control (Part I)
With this patch dunecontrol will work even if the path to the module
contains spaces. Unfortunately, the tests for dune modules will still
not work as I could not figure out how to use quoting in the CPP_FLAGS.

diff --git a/bin/dunecontrol b/bin/dunecontrol
--- a/bin/dunecontrol
+++ b/bin/dunecontrol
@@ -58,7 +58,7 @@ canonicalpath(){
      echo Usage: canonicalpath path >&2
      return 1
   fi
-  dirname `canonicalname "$1"`
+  dirname "`canonicalname "$1"`"
 }
 
 checkdebug () {
@@ -78,7 +78,7 @@ if test "x$DEBUG" = "xyes"; then
   set -v
 fi
 
-export PREFIX_DIR="`canonicalpath $0`/.."
+export PREFIX_DIR="`canonicalpath "$0"`/.."
 
 # create PKG_CONFIG_PATH for installed dune modules
 if test -d "$PREFIX_DIR/lib/pkgconfig"; then
@@ -91,7 +91,7 @@ fi
 ###############################################
 
 onbuildfailure() {
-  echo "Terminating $(basename $0) due to previous errors!" >&2
+  echo "Terminating $(basename "$0") due to previous errors!" >&2
   exit 1
 }
 
@@ -136,14 +136,14 @@ build_module() {
     local runcommand=run_$command
 
     # build the modules
-    local path=$(eval "echo \$PATH_${module}")
+    local path="$(eval "echo \$PATH_${module}")"
     eval echo "--- calling $command for \$NAME_${module} ---"
 	trap onbuildfailure EXIT
     if ! (
       set -e
       cd "$path"
       export module
-      eval_control $runcommand $path/$CONTROL
+      eval_control $runcommand "$path/$CONTROL"
     ); then eval echo "--- Failed to build \$NAME_${module} ---"; exit 1; fi
 	trap onfailure EXIT
 
@@ -537,15 +537,15 @@ run_default_autogen () {
        ( test -d .svn || test -d .git || test -d CVS || test -f stamp-vc ); then
       sort_modules $FOUND_MODULES
       for m in $FOUND_MODULES; do
-        path=$(eval "echo \$PATH_$m")
-        MODULE_PATHS="$MODULE_PATHS$path "
+        path="$(eval "echo \$PATH_$m")"
+        MODULE_PATHS="$MODULE_PATHS\"$path\" "
       done
       if test -f autogen.sh; then
         eval echo "WARNING: \$NAME_$module contains obsolete autogen.sh," \
             >&2
         echo "         dune-autogen is used instead." >&2
       fi
-      eval "$PREFIX_DIR/bin/dune-autogen" "$MODULE_PATHS" "$PARAMS" || exit 1
+      eval "\"$PREFIX_DIR/bin/dune-autogen\"" "$MODULE_PATHS" "$PARAMS" || exit 1
     else
       echo Skipping dune-autogen
     fi
@@ -571,7 +571,7 @@ run_default_configure () {
     # get dependencies & suggestions
     sort_modules $module
     for m in $MODULES; do
-      path=$(eval "echo \$PATH_$m")
+      path="$(eval "echo \$PATH_$m")"
       if test "x$LOCAL_USE_CMAKE" = "xyes"; then
           #
           # Translate the configure PARMS to cmake
@@ -686,13 +686,13 @@ run_default_git () {
 ###
 
 onfailure() {
-  echo "Execution of $(basename $0) terminated due to errors!" >&2
+  echo "Execution of $(basename "$0") terminated due to errors!" >&2
   exit 1
 }
 
 usage () {
   (
-    echo "Usage: $(basename $0) [OPTIONS] COMMANDS [COMMAND-OPTIONS]"
+    echo "Usage: $(basename "$0") [OPTIONS] COMMANDS [COMMAND-OPTIONS]"
     echo ""
     echo "  Execute COMMANDS for all Dune modules found. All entries in the"
     echo "  DUNE_CONTROL_PATH variable are scanned recursively for Dune modules."
@@ -747,7 +747,7 @@ create_module_list() {
     fi
 
     export MODULES=
-    RESUME="`cat $RESUME_FILE`"
+    RESUME="`cat "$RESUME_FILE"`"
     for a in $RESUME ; do
         export NAME_`fix_variable_name $a`="$a"
         fix_and_assign MODULE "$a"
@@ -940,7 +940,7 @@ case "$command" in
     create_module_list
     DUNE_CONTROL_PATH=""
     for mod in $MODULES; do
-      path=$(eval echo \$PATH_$mod)
+      path="$(eval echo \$PATH_$mod)"
       name=$(eval echo \$NAME_$mod)
       if test -f "$path/dune.module"; then
         export DUNE_CONTROL_PATH="$DUNE_CONTROL_PATH:$path/dune.module"
@@ -982,7 +982,7 @@ case "$command" in
       exit 1
     fi
     mainmod=`echo $SEARCH_MODULES`
-    eval mainmodpath=\$PATH_$mainmod
+    eval mainmodpath="\$PATH_$mainmod"
     fname="$mainmodpath/dependencies.m4"
     name=`eval echo \\${NAME_$mainmod}`
     version=`eval echo \\${VERS_$mainmod}`
@@ -1044,7 +1044,7 @@ case "$command" in
     echo "        suggests $suggestsall"
       AC_MACRO_DIR="."
       test ! -d m4 || AC_MACRO_DIR=m4
-    cat > $fname <<EOF
+    cat > "$fname" <<EOF
 # dependencies.m4 generated by dunecontrol
 
 m4_define([DUNE_AC_INIT],[
@@ -1067,7 +1067,7 @@ EOF
       mod=$(fix_variable_name $name)
       MOD=`echo $mod | tr [:lower:] [:upper:]`
       if test "x$(eval echo \$HAVE_$mod)" = "x"; then
-        cat >> $fname <<EOF
+        cat >> "$fname" <<EOF
   ### add a conditional check for $name,
   # just in case the module is not available at autogen time
   AM_CONDITIONAL([HAVE_${MOD}], false)
@@ -1080,7 +1080,7 @@ EOF
     for mod in $SORTEDMODULES_DEPS; do
       name=`eval echo \\$NAME_$mod`
       MOD=`echo $mod | tr [:lower:] [:upper:]`
-      cat >> $fname <<EOF
+      cat >> "$fname" <<EOF
   ### check dependency $name
   # invoke checks required by this module
   AC_REQUIRE([${MOD}_CHECKS])
@@ -1095,7 +1095,7 @@ EOF
     for mod in $SORTEDMODULES_SUGS; do
       name=`eval echo \\$NAME_$mod`
       MOD=`echo $mod | tr [:lower:] [:upper:]`
-      cat >> $fname <<EOF
+      cat >> "$fname" <<EOF
   ### check suggestion $name
   # invoke checks required by this module
   AC_REQUIRE([${MOD}_CHECKS])
@@ -1112,12 +1112,12 @@ EOF
       mod=$mainmod
       name=`eval echo \\$NAME_$mod`
       MOD=`echo $mod | tr [:lower:] [:upper:]`
-      cat >> $fname <<EOF
+      cat >> "$fname" <<EOF
   ### invoke checks for $name
   AC_REQUIRE([${MOD}_CHECKS])
 EOF
     fi
-    cat >> $fname <<EOF
+    cat >> "$fname" <<EOF
 ])
 EOF
   ;;
@@ -1152,7 +1152,7 @@ EOF
 
       if test -n "$RESUME_FILE"; then
           # remove the current module from the resume file
-          modules_togo=`cat $RESUME_FILE`
+          modules_togo=`cat "$RESUME_FILE"`
           for mod_togo in $modules_togo ; do
               if test "$mod_togo" != "$mod" ; then
                   echo "$mod_togo"
