redirect error messages to &2 and not to /dev/stderr
[[Imported from SVN: r5177]]

diff --git a/bin/dunecontrol b/bin/dunecontrol
--- a/bin/dunecontrol
+++ b/bin/dunecontrol
@@ -18,13 +18,13 @@ fi
 
 canonicalname(){
   if test $# -ne 1; then
-     echo Usage: canonicalname path > /dev/stderr
+     echo Usage: canonicalname path >&2
      return 1
   fi
   name="$1"
   while test -L "$name"; do
     if ! test -e "$name"; then
-      echo $name: file not found > /dev/stderr
+      echo $name: file not found >&2
       return 1
     fi
     if newname="`readlink $name`"; then
@@ -38,7 +38,7 @@ canonicalname(){
 
 canonicalpath(){
   if test $# -ne 1; then
-     echo Usage: canonicalpath path > /dev/stderr
+     echo Usage: canonicalpath path >&2
      return 1
   fi
   (cd $(dirname $(canonicalname $1)) && pwd)
@@ -240,9 +240,8 @@ run_default_autogen () {
       fi
     done
     if test -f autogen.sh; then
-      eval echo "WARNING: \$NAME_$module contains obsolete autogen.sh," \
-		  > /dev/stderr
-	  echo "         dune-autogen is used instead." > /dev/stderr
+      eval echo "WARNING: \$NAME_$module contains obsolete autogen.sh," >&2
+	  echo "         dune-autogen is used instead." >&2
     fi
 #    eval ./autogen.sh "$M4_PATH" "$PARAMS" || exit 1
     eval "$COMMAND_DIR/dune-autogen" "$M4_PATH" "$PARAMS" || exit 1
@@ -277,8 +276,8 @@ run_default_configure () {
     eval ./configure "$PARAMS" || exit 1
   else
     if test -f configure.in || test -f configure.ac; then
-      echo "ERROR: configure.[in|ac] found, but configure missing" > /dev/stderr
-      echo "did you forget to run autoconf?" > /dev/stderr
+      echo "ERROR: configure.[in|ac] found, but configure missing" >&2
+      echo "did you forget to run autoconf?" >&2
       exit 1
     fi
   fi
@@ -312,7 +311,7 @@ run_default_svn () {
 ###
 
 onfailure() {
-  echo "Execution of $(basename $0) terminated due to errors!" > /dev/stderr
+  echo "Execution of $(basename $0) terminated due to errors!" >&2
   exit 1
 }
 
@@ -345,7 +344,7 @@ usage () {
     printf "  \`export'\trun eval \`dunecontrol export\` to save the list of\n"
     printf "  \t\tdune.module files to the DUNE_CONTROL_PATH variable\n"
     echo
-  )  > /dev/stderr
+  )  >&2
 }
 
 # create the module list
@@ -408,15 +407,15 @@ while test $# -gt 0; do
     --opts=*)
       if test "x$arg" = "x"; then
         usage
-        echo "ERROR: Parameter for --opts is missing"  > /dev/stderr
-        echo  > /dev/stderr
+        echo "ERROR: Parameter for --opts is missing"  >&2
+        echo  >&2
         exit 1;
       fi
       DUNE_OPTS_FILE=$(canonicalpath $arg)/$(basename $arg)
       if ! test -r "$DUNE_OPTS_FILE"; then
         usage
-        echo "ERROR: could not read opts file \"$DUNE_OPTS_FILE\""  > /dev/stderr
-        echo  > /dev/stderr
+        echo "ERROR: could not read opts file \"$DUNE_OPTS_FILE\""  >&2
+        echo  >&2
         exit 1;
       fi
     ;;
@@ -427,7 +426,7 @@ while test $# -gt 0; do
         export ${COMMAND}_FLAGS="$arg"
       else
         usage
-        echo "ERROR: unknown option \"$option\""  > /dev/stderr
+        echo "ERROR: unknown option \"$option\""  >&2
         exit 1
       fi
     ;;
@@ -442,8 +441,8 @@ while test $# -gt 0; do
     --module=*)
       if test "x$arg" = "x"; then
         usage
-        echo "ERROR: Parameter for --module is missing"  > /dev/stderr
-        echo  > /dev/stderr
+        echo "ERROR: Parameter for --module is missing"  >&2
+        echo  >&2
         exit 1;
       fi
 	  for a in `echo $arg | tr ',' ' '`; do
@@ -455,8 +454,8 @@ while test $# -gt 0; do
     --only=*)
       if test "x$arg" = "x"; then
         usage
-        echo "ERROR: Parameter for --only is missing"  > /dev/stderr
-        echo  > /dev/stderr
+        echo "ERROR: Parameter for --only is missing"  >&2
+        echo  >&2
         exit 1;
       fi
 	  for a in `echo $arg | tr ',' ' '`; do
@@ -469,8 +468,8 @@ while test $# -gt 0; do
     --debug) true ;;
     --*)
       usage
-      echo "ERROR: Unknown option \`$option'"  > /dev/stderr
-      echo  > /dev/stderr
+      echo "ERROR: Unknown option \`$option'"  >&2
+      echo  >&2
 	  exit 1
       ;;
     *)
@@ -498,7 +497,7 @@ case "$command" in
   print)
     create_module_list
     eval "print_module_list ' ' $MODULES"
-    echo > /dev/stderr
+    echo >&2
     ;;
   m4depends)
     find_modules_in_path
@@ -618,7 +617,7 @@ EOF
       echo "--- done ---"
 	else
       usage
-      echo "ERROR: unknown command \"$command\""  > /dev/stderr
+      echo "ERROR: unknown command \"$command\""  >&2
       exit 1
     fi
     ;;
diff --git a/bin/duneproject b/bin/duneproject
--- a/bin/duneproject
+++ b/bin/duneproject
@@ -11,13 +11,13 @@ set -e
 
 canonicalname(){
   if test $# -ne 1; then
-     echo Usage: canonicalname path > /dev/stderr
+     echo Usage: canonicalname path >&2
      return 1
   fi
   name="$1"
   while test -L "$name"; do
     if ! test -e "$name"; then
-      echo $name: file not found > /dev/stderr
+      echo $name: file not found >&2
       return 1
     fi
     if newname="`readlink $name`"; then
@@ -31,7 +31,7 @@ canonicalname(){
 
 canonicalpath(){
   if test $# -ne 1; then
-     echo Usage: canonicalpath path > /dev/stderr
+     echo Usage: canonicalpath path >&2
      return 1
   fi
   (cd $(dirname $(canonicalname $1)) && pwd)
@@ -39,7 +39,7 @@ canonicalpath(){
 
 pkg_config_dependencies(){
     if test $# -ne 1; then
-	echo Usage: pkg_config_dependencies name > /dev/stderr
+	echo Usage: pkg_config_dependencies name >&2
 	return 1
     fi
     name="$1"
@@ -62,11 +62,11 @@ modulesexist(){
 	  fi
       done
       if [ "$found" = "0" ]; then
-	  echo "ERROR:">/dev/stderr
-	  echo "Module with name $dep was not found" > /dev/stderr
-	  echo "Did you forget to specify it's location" > /dev/stderr
-	  echo "in the DUNE_CONTROL_PATH variable?"> /dev/stderr
-	  echo >/dev/stderr
+	  echo "ERROR:">&2
+	  echo "Module with name $dep was not found" >&2
+	  echo "Did you forget to specify it's location" >&2
+	  echo "in the DUNE_CONTROL_PATH variable?">&2
+	  echo >&2
 	  allfound=1
       fi
   done
@@ -147,13 +147,13 @@ ALL_MODULES="`echo $SRC_MODULES $PKG_MODULES | tr ' ' '\n' | sort | uniq`"
 
 
 if [ "$ALL_MODULES" = "" ]; then
-  echo "ERROR">/dev/stderr
-  echo "No dune modules were found!">/dev/stderr
-  echo "Did you forget to specify the places where ">/dev/stderr
-  echo "you installed your modules in the ">/dev/stderr
-  echo "DUNE_CONTROL_PATH environment variable">/dev/stderr
-  echo "and adjusted the PKG_CONFIG_PATH environment">/dev/stderr
-  echo "accordingly?" >/dev/stderr
+  echo "ERROR">&2
+  echo "No dune modules were found!">&2
+  echo "Did you forget to specify the places where ">&2
+  echo "you installed your modules in the ">&2
+  echo "DUNE_CONTROL_PATH environment variable">&2
+  echo "and adjusted the PKG_CONFIG_PATH environment">&2
+  echo "accordingly?" >&2
   exit 1;
 fi
 
diff --git a/bin/mpi-config b/bin/mpi-config
--- a/bin/mpi-config
+++ b/bin/mpi-config
@@ -4,13 +4,13 @@ set -e
 
 canonicalname(){
   if test $# -ne 1; then
-     echo Usage: canonicalname path > /dev/stderr
+     echo Usage: canonicalname path >&2
      return 1
   fi
   name="$1"
   while test -L "$name"; do
     if ! test -e "$name"; then
-      echo $name: file not found > /dev/stderr
+      echo $name: file not found >&2
       return 1
     fi
     if newname="`readlink $name`"; then
@@ -24,7 +24,7 @@ canonicalname(){
 
 canonicalpath(){
   if test $# -ne 1; then
-     echo Usage: canonicalpath path > /dev/stderr
+     echo Usage: canonicalpath path >&2
      return 1
   fi
   (cd $(dirname $(canonicalname $1)) && pwd)
@@ -50,8 +50,7 @@ findm4dir() {
     echo "$M4DIR"
     return
   fi
-  echo "ERROR: could not find mpi-config.m4! Incomplete installation?" \
-    > /dev/stderr
+  echo "ERROR: could not find mpi-config.m4! Incomplete installation?" >&2
   exit 1
 }
 
