'only' option
[[Imported from SVN: r4592]]

diff --git a/bin/dunecontrol b/bin/dunecontrol
--- a/bin/dunecontrol
+++ b/bin/dunecontrol
@@ -87,6 +87,9 @@ sort_modules() {
   for m in "$@"; do
     _sort_module $m
   done
+  if test x"$ONLY" != x; then
+	SORTEDMODULES=$ONLY
+  fi
   export MODULES=$SORTEDMODULES
 }
 
@@ -388,6 +391,16 @@ while test $# -gt 0; do
         echo
         exit 1;
       fi
+      MODULE=$arg
+    ;;
+    --only=*)
+      if test "x$arg" == "x"; then
+        usage
+        echo "ERROR: Parameter for --only is missing"
+        echo
+        exit 1;
+      fi
+      ONLY=$arg
       MODULE=$arg
     ;;
     --debug) true ;;
