merged fix for duneproject from trunk
[[Imported from SVN: r4887]]

diff --git a/bin/duneproject b/bin/duneproject
--- a/bin/duneproject
+++ b/bin/duneproject
@@ -283,7 +283,7 @@ cat > "$PROJECT/autogen.sh" <<A_DELIM
 set -e
 
 usage () {
-    echo "Usage: ./autogen.sh [options]"
+    echo "Usage: ./autogen.sh DUNE_COMMON_DIR [options]"
     echo "  --ac=, --acversion=VERSION   use a specific VERSION of autoconf"
     echo "  --am=, --amversion=VERSION   use a specific VERSION of automake"
     echo "  -h,    --help                you already found this :-)"
@@ -316,11 +316,14 @@ for OPT in "\$@"; do
             if test -d "\$OPT/m4"; then
               ACLOCAL_FLAGS="\$ACLOCAL_FLAGS -I \$OPT/m4"
             fi
-            if test -d "$OPT/share/aclocal"; then
-              ACLOCAL_FLAGS="$ACLOCAL_FLAGS -I $OPT/share/aclocal"
-            fi
             if test -d "\$OPT/am"; then
               am_dir="\$OPT/am"
+            fi
+            if test -d "\$OPT/share/aclocal"; then
+              ACLOCAL_FLAGS="\$ACLOCAL_FLAGS -I \$OPT/share/aclocal"
+            fi
+            if test -d "\$OPT/share/dune-common/am"; then
+              am_dir="\$OPT/share/dune-common/am"
             fi
             ;;
     esac
@@ -363,9 +366,16 @@ echo "--> autoheader..."
 autoheader\$ACVERSION
 
 # create a link to the dune-common am directory
-echo "--> linking dune-common/am..."
-rm -f am
-ln -s \$am_dir am
+if [ -n "\$am_dir" ] && [ -d \$am_dir ]; then
+  echo "--> linking dune-common/am..."
+  rm -f am
+  ln -s \$am_dir am
+else
+  echo
+  echo "Error: Could not find dune-common/am!"
+  usage
+  exit 1
+fi
 
 # call automake/conf
 echo "--> automake..."
