Revert "Make finding *.la files non-fatal."
This reverts commit 21dbaefe75b761ab6ade8ccf73e33ba35b0c66b3.
Thus if libtool libs are found, then we abort again.
Please do not merge to the release.

diff --git a/bin/dunecontrol b/bin/dunecontrol
--- a/bin/dunecontrol
+++ b/bin/dunecontrol
@@ -717,7 +717,8 @@ run_default_configure () {
       cd "$ABS_BUILDDIR"
       # check for libtool libs, which might break modules depending on this module
       test -n "`find . -name \*.la`" && \
-          echo "Warning: your build directory $ABS_BUILDDIR contains libtool built libraries, please cleanup"
+          echo "Error: your build directory $ABS_BUILDDIR contains libtool built libraries, please cleanup" && \
+          exit 1
       echo "$PREPARAMS $CMAKE -DCMAKE_MODULE_PATH=\"$CMAKE_MODULE_PATH\" $CMAKE_PARAMS $CMAKE_FLAGS \"$SRCDIR\""
       eval $PREPARAMS $CMAKE "-DCMAKE_MODULE_PATH=\"$CMAKE_MODULE_PATH\" $CMAKE_PARAMS $CMAKE_FLAGS \"$SRCDIR\"" || exit 1
     else
