I made myself a late christmas present...
support for out-of-source builds in Dune.

You call dunecontrol with a parameter --builddir=NAME
dunecontrol will create a subdirectory NAME inside each 
module and do an out-of-source build there.

Not necessarily all modules support out-of-source, but at 
least common/istl did work.

[[Imported from SVN: r5813]]

diff --git a/bin/dunecontrol b/bin/dunecontrol
--- a/bin/dunecontrol
+++ b/bin/dunecontrol
@@ -172,10 +172,8 @@ COMMANDS="update autogen configure make all exec status svn"
 update_HELP="updated all modules from the repository"
 autogen_HELP="run the autogen.sh script for each module"
 configure_HELP="run configure for each module"
-       # "NOTE: the --with-dune* parameters will be generated by dunecontrol"
 make_HELP="run make for each module"
 all_HELP="\trun 'autogen', 'configure' and 'make' command for each module"
-       # "NOTE: run all for an initial setup"
 exec_HELP="execute an arbitrary command in each module directory"
 status_HELP="show vc status for all modules"
 svn_HELP="\trun svn command for each svn managed module"
@@ -312,14 +310,26 @@ run_default_configure () {
       if test -d "$path/share/aclocal"; then
           ACLOCAL_FLAGS="$ACLOCAL_FLAGS -I $path/share/aclocal"
       fi
-	  PARAMS="$PARAMS \"--with-$name=$path\""
+	  if test -d "$path/$BUILDDIR"; then
+	    PARAMS="$PARAMS \"--with-$name=$path/$BUILDDIR\""
+	  else
+	    PARAMS="$PARAMS \"--with-$name=$path\""
+	  fi
 	done
 	if test "x$HAVE_duneweb" == "xyes"; then
 	  PARAMS="$PARAMS \"--with-duneweb=$PATH_duneweb\""
 	fi
 	PARAMS="$PARAMS ACLOCAL_AMFLAGS=\"$ACLOCAL_FLAGS\""
     echo ./configure "$PARAMS"
-    eval ./configure "$PARAMS" || exit 1
+    # create build directory of requested
+	if test -n "$BUILDDIR"; then
+	  test -d "$BUILDDIR" || mkdir "$BUILDDIR"
+	  SRCDIR="$PWD"
+	  cd "$BUILDDIR"
+      eval "$SRCDIR/configure" "$PARAMS" || exit 1
+	else
+      eval ./configure "$PARAMS" || exit 1
+	fi
   else
     if test -f configure.in || test -f configure.ac; then
       echo "ERROR: configure.[in|ac] found, but configure missing." >&2
@@ -334,6 +344,7 @@ run_default_configure () {
 }
 
 run_default_make () {
+  test ! -d "$BUILDDIR" || cd "$BUILDDIR"
   PARAMS="$CMD_FLAGS"
   echo make "$PARAMS"
   eval $MAKE "$PARAMS"
@@ -386,6 +397,8 @@ usage () {
     echo "                     not built successfully on the previous run)"
     echo "      --opts=FILE    load default options from FILE"
     echo "                     (see dune-common/doc/example.opts)"
+    echo "      --builddir=NAME make out-of-source builds in a subdir NAME."
+	echo "                     This directory is create inside each module."
     echo "      --[COMMAND]-opts=opts   set options for COMMAND"
     echo "                     (this is mainly useful for the all COMMAND)"
     echo "COMMANDS:"
@@ -506,6 +519,15 @@ while test $# -gt 0; do
         export SEARCH_MODULES="$SEARCH_MODULES $MODULE"
         export ONLY="$ONLY $MODULE"
       done
+	;;
+    --builddir=*)
+      if test "x$arg" = "x"; then
+        usage
+        echo "ERROR: Parameter for --builddir is missing"  >&2
+        echo  >&2
+        exit 1;
+      fi
+	  export BUILDDIR=$arg
 	;;
 	--skipversioncheck)
       export SKIPVERSIONCHECK=yes
