many fixes for target check-log
[[Imported from SVN: r2168]]

diff --git a/am/checklog b/am/checklog
--- a/am/checklog
+++ b/am/checklog
@@ -15,13 +15,13 @@ check-log: $(top_srcdir)/bin/check-log-store
 check-log:
 	rm -f $(LOG_FILE)
 
-check-log: check-log-lib
+check-log: check-log-libs
 check-log: check-log-build
 check-log: check-log-test
 check-log: check-log-sources
 check-log: check-log-dir
 
-check-log-lib: check-log-lib-recursive
+check-log-libs: check-log-libs-recursive
 check-log-build: check-log-build-recursive
 check-log-test: check-log-test-recursive
 check-log-sources: check-log-sources-recursive
@@ -29,35 +29,63 @@ check-log-dir: check-log-dir-recursive
 
 check-log-sources-am:
 	$(LOG_SET_OPTIONS); \
-	$(MAKE) sourcescheck-am 2>&1> $(LOG_FILE); \
-	$(LOG_STORE) "sources" "Makefile.am" "$$path" $(LOG_FILE);
+	$(MAKE) sourcescheck-am >& $(LOG_FILE); \
+	$(LOG_STORE) "sources" "Makefile.am" "$$path" $(LOG_FILE) >& /dev/null;
 
 check-log-libs-am:
 	$(LOG_SET_OPTIONS); \
-	for target in $(lib_LTLIBRARIES); do \
-	  $(MAKE) $$i 2>&1> $(LOG_FILE); \
-	  $(LOG_STORE) "build" "$$target" "$$path" $(LOG_FILE); \
+	for target in $(LTLIBRARIES); do \
+	  $(MAKE) $$i >& $(LOG_FILE); \
+	  $(LOG_STORE) "build" "$$target" "$$path" $(LOG_FILE) >& /dev/null; \
 	done;
 
 check-log-build-am:
 	$(LOG_SET_OPTIONS); \
 	for target in $(check_PROGRAMS) $(PROGRAMS); do \
-	  $(MAKE) $$i 2>&1> $(LOG_FILE); \
-	  $(LOG_STORE) "build" "$$target" "$$path" $(LOG_FILE); \
+	  $(MAKE) $$target >& $(LOG_FILE); \
+	  $(LOG_STORE) "build" "$$target" "$$path" $(LOG_FILE) >& /dev/null; \
 	done;
 
 check-log-test-am:
+	@LOG () { \
+	  ( echo "$$1"; echo ) > $(LOG_FILE).2; \
+	  cat $(LOG_FILE) >> $(LOG_FILE).2; \
+	  mv $(LOG_FILE).2 $(LOG_FILE); \
+	}; \
 	$(LOG_SET_OPTIONS); \
-	for test in $(TESTS); do \
-	  ./$$test 2>&1> $(LOG_FILE); \
-	  $(LOG_STORE) "run" "$$test" "$$path" $(LOG_FILE); \
+	for tst in $(TESTS); do \
+	  if test -f ./$$tst; then dir=./; \
+	  elif test -f $$tst; then dir=; \
+	  else dir="$(srcdir)/"; fi; \
+	  if $(TESTS_ENVIRONMENT) $${dir}$$tst >& $(LOG_FILE); then \
+	    case " $(XFAIL_TESTS) " in \
+	    *" $$tst "*) \
+	      LOG "ERROR: XPASS ($$tst)"; \
+	    ;; \
+	    *) \
+	      LOG "SUCCESS: PASS ($$tst)"; \
+	    ;; \
+	    esac; \
+	  elif test $$? -ne 77; then \
+	    case " $(XFAIL_TESTS) " in \
+	    *" $$tst "*) \
+	      LOG "SUCCESS: XFAIL ($$tst)"; \
+	    ;; \
+	    *) \
+	      LOG "ERROR: FAIL ($$tst)"; \
+	    ;; \
+	    esac; \
+	  else \
+	    LOG "WARNING: SKIP ($$tst)"; \
+	  fi; \
+	  $(LOG_STORE) "run" "$$tst" "$$path" $(LOG_FILE) >& /dev/null; \
 	done;
 
 check-log-dir-am:
 	$(LOG_SET_OPTIONS); \
-	$(LOG_STORE) "dir" "$$dir" "$$ppath"
+	$(LOG_STORE) "dir" "$$dir" "$$ppath" >& /dev/null
 
-check-log-lib-recursive \
+check-log-libs-recursive \
 check-log-build-recursive \
 check-log-test-recursive \
 check-log-sources-recursive \
